### PR TITLE
Various Improvements and Cleanup

### PR DESCRIPTION
**Pull request by infininight**
Got a request to add a smalltalk bundle to the 2.0 installer and this bundle appeared to be the best around. Made some minor improvements as I reviewed the bundle and corrected a recursion bug in one regexp that was causing some speed issues.

I have updated the readme to be 2.0 specific as a few of the grammar changes will not work for 1.x. The way we handled this in our bundles is to create a branch or tag at the last commit supported by 1.x so that can still be obtained for those users. (The 2.0 changes are support by [@github/linguist](https://github.com/github/linguist).)

Ask if you have any questions about the changes made.

### CODE REVIEW

**Comment by infininight** [comment]
I've gone ahead and pushed by fork in the bundle installer so the user can get it installed but I'll delay before I announce the addition to give time for feedback on these changes.

**Comment by tomas-stefano** [comment]
Sorry, I miss this from my notifications. IMHO, github notifications is not that great mainly when you're working between different organisations and projects. I just spotted this when I created a script to returns all open PR from someone's profile or organisation. 

Anyway I will take a look on this on this weekend.

**Comment by infininight** [comment]
@tomas-stefano Not to take away from the fanciness of your script. :) You can click on "Pull Requests" in the header then enter the following query:

    is:open is:pr user:tomas-stefano

Extend it to a organization as well with `user:org` added on the end, bookmark for easy reference.

**Comment by tomas-stefano** [comment]
Thank you for explaining, but I didn't enter on this repo for a long time, so I was unaware of the PR's since I miss the notification. Still my bad. But thank you for this. It looks good, I will merge now.

**Pull request merged**
